apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.namespace }}
data:
  maxmemory-policy: '{{ .Values.configmap.data.maxmemory-policy }}'
  maxmemory: '{{ .Values.configmap.data.maxmemory }}'
